### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by DubyaDude** [RubyEdge/SigSpec#2]
- [ ] Create build actions.
- [ ] Create a proper Wiki.
- [ ] Add UI for development.
- [ ] Create a command line tool.
- [ ] Add more XML comments to generation.
- [ ] Update README to reflect changes.
